version: '3'
services:
  node:
    image: node:14
    working_dir: /app
    tty: true
    ports:
      - "80:3000"
    volumes:
      - ./app:/app
    command: [sh, -c, npm install && DEBUG=node:* npm run devstart ]

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"